name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: myeidos-frontend
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          VITE_PRIVATE_KEY: ${{ secrets.VITE_PRIVATE_KEY }}
          VITE_CLIENT_EMAIL: ${{ secrets.VITE_CLIENT_EMAIL }}
          VITE_BUCKET_NAME: ${{ secrets.VITE_BUCKET_NAME }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -f ../Dockerfile --build-arg VITE_PRIVATE_KEY='${{ secrets.VITE_PRIVATE_KEY }}' --build-arg VITE_CLIENT_EMAIL='${{ secrets.VITE_CLIENT_EMAIL }}' --build-arg VITE_BUCKET_NAME='${{ secrets.VITE_BUCKET_NAME }}' -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
